"""GitHub-backed Agent Devel orchestration.

This module implements the safe "Scaffold Modules" strategy for Agent Builder,
App Builder, Game Builder, and Web Builder workflows.

The agent may create repositories, write declarative/source scaffolds, open pull
requests, and report incidents. It deliberately does not execute generated code
on the host running ODYN AI.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

SUPPORTED_PROJECT_TYPES = frozenset(
    {
        "agent_builder_code",
        "agent_builder_no_code",
        "app_builder",
        "game_builder",
        "web_builder",
    }
)


@dataclass(frozen=True)
class ScaffoldFile:
    """A single file emitted by a controlled project scaffold."""

    path: str
    content: str


def _common_files(project_type: str, description: str) -> tuple[ScaffoldFile, ...]:
    return (
        ScaffoldFile(
            "README.md",
            f"""# {description}

Generated by ODYN AI Agent Devel using the Scaffold Modules strategy.

- Project type: {project_type}
- Generated source is pushed to GitHub for review and CI.
- Generated code is not executed by this agent.
- Changes should be delivered through auditable pull requests.
""",
        ),
    )


def _project_files(project_type: str) -> tuple[ScaffoldFile, ...]:
    templates: dict[str, tuple[ScaffoldFile, ...]] = {
        "web_builder": (
            ScaffoldFile(
                "index.html",
                """<!doctype html>
<html lang="pl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ODYN Web Scaffold</title>
</head>
<body>
  <main>
    <h1>Web App</h1>
    <p>Scaffold generated by ODYN AI.</p>
  </main>
</body>
</html>
""",
            ),
        ),
        "game_builder": (
            ScaffoldFile(
                "main.py",
                """def main() -> None:
    print("Game scaffold generated by ODYN AI")


if __name__ == "__main__":
    main()
""",
            ),
        ),
        "app_builder": (
            ScaffoldFile(
                "app/README.md",
                """# App Builder

Application scaffold. Add platform-specific UI and service modules here.
""",
            ),
        ),
        "agent_builder_code": (
            ScaffoldFile(
                "agent.py",
                """def run_agent(task: str) -> str:
    return f"Agent scaffold received: {task}"
""",
            ),
        ),
        "agent_builder_no_code": (
            ScaffoldFile(
                "agent.yaml",
                """version: 1
name: odyn-agent-scaffold
steps:
  - id: input
    type: input
  - id: response
    type: response
""",
            ),
        ),
    }
    return templates[project_type]


class GitHubAgentBuilder:
    """Controlled GitHub operator for ODYN's Agent Devel workflows.

    github_factory is injectable so the module can be tested without network
    access or real credentials.
    """

    def __init__(
        self,
        token: str,
        *,
        github_factory: Callable[[Any], Any] | None = None,
    ) -> None:
        if not token or not token.strip():
            raise ValueError("GitHub token jest wymagany.")

        if github_factory is None:
            from github import Auth, Github

            github_factory = lambda auth: Github(auth=auth)
            auth = Auth.Token(token)
        else:
            auth = token

        self.gh = github_factory(auth)

    def _scaffold_files(
        self,
        project_type: str,
        description: str,
    ) -> tuple[ScaffoldFile, ...]:
        if project_type not in SUPPORTED_PROJECT_TYPES:
            supported = ", ".join(sorted(SUPPORTED_PROJECT_TYPES))
            raise ValueError(
                f"Nieobsługiwany typ projektu: {project_type}. "
                f"Dozwolone: {supported}"
            )
        return _common_files(project_type, description) + _project_files(project_type)

    def create_project_scaffold(
        self,
        repo_name: str,
        description: str,
        project_type: str,
    ) -> str:
        """Create a private repository and push a controlled source scaffold."""

        if not repo_name or not repo_name.strip():
            raise ValueError("Nazwa repozytorium jest wymagana.")

        files = self._scaffold_files(project_type, description)
        user = self.gh.get_user()

        try:
            repo = user.create_repo(
                repo_name,
                description=description,
                private=True,
            )
            for scaffold_file in files:
                repo.create_file(
                    scaffold_file.path,
                    f"chore: add {project_type} scaffold ({scaffold_file.path})",
                    scaffold_file.content,
                    branch="main",
                )
            return (
                f"Repozytorium wdrożone pomyślnie. Architektura {project_type}. "
                f"URL: {repo.html_url}"
            )
        except Exception as exc:
            return f"Błąd tworzenia repozytorium (Sovereign limit): {exc}"

    def automate_pull_request(
        self,
        repo_name: str,
        title: str,
        body: str,
        head_branch: str,
        base_branch: str,
    ) -> str:
        """Open an auditable PR from a generated branch into the base branch."""

        if not head_branch or not base_branch:
            raise ValueError("Head i base branch są wymagane.")

        repo = self.gh.get_repo(repo_name)
        try:
            pr = repo.create_pull(
                title=title,
                body=body,
                head=head_branch,
                base=base_branch,
            )
            return f"Wygenerowano ulepszenia. Otwarto Pull Request (PR): {pr.html_url}"
        except Exception as exc:
            return f"Awaria infrastruktury PR: {exc}"

    def report_retrospective_issue(
        self,
        repo_name: str,
        title: str,
        body: str,
    ) -> str:
        """Record a development incident as a GitHub Issue."""

        repo = self.gh.get_repo(repo_name)
        try:
            issue = repo.create_issue(title=title, body=body)
            return f"Zarejestrowano incydent deweloperski: {issue.html_url}"
        except Exception as exc:
            return f"Niepowodzenie zgłoszenia: {exc}"
