from __future__ import annotations

import pytest

from nexus_core.plugins.github_agent import GitHubAgentBuilder, SUPPORTED_PROJECT_TYPES


class FakeRepo:
    def __init__(self, name: str = "demo") -> None:
        self.name = name
        self.html_url = f"https://github.com/test/{name}"
        self.files: list[tuple[str, str, str, str]] = []
        self.pull_requests: list[dict[str, str]] = []
        self.issues: list[dict[str, str]] = []

    def create_file(self, path: str, message: str, content: str, branch: str) -> None:
        self.files.append((path, message, content, branch))

    def create_pull(self, *, title: str, body: str, head: str, base: str):
        self.pull_requests.append(
            {"title": title, "body": body, "head": head, "base": base}
        )
        return type("PR", (), {"html_url": f"{self.html_url}/pull/1"})()

    def create_issue(self, *, title: str, body: str):
        self.issues.append({"title": title, "body": body})
        return type("Issue", (), {"html_url": f"{self.html_url}/issues/1"})()


class FakeUser:
    def __init__(self) -> None:
        self.repos: list[FakeRepo] = []

    def create_repo(self, name: str, *, description: str, private: bool):
        repo = FakeRepo(name)
        self.repos.append(repo)
        return repo


class FakeGithub:
    def __init__(self, auth) -> None:
        self.auth = auth
        self.user = FakeUser()

    def get_user(self) -> FakeUser:
        return self.user

    def get_repo(self, repo_name: str) -> FakeRepo:
        return next(repo for repo in self.user.repos if repo.name == repo_name)


@pytest.fixture
def builder() -> GitHubAgentBuilder:
    return GitHubAgentBuilder(
        "test-token",
        github_factory=lambda auth: FakeGithub(auth),
    )


def test_supported_builder_modes_are_explicit() -> None:
    assert {
        "agent_builder_code",
        "agent_builder_no_code",
        "app_builder",
        "game_builder",
        "web_builder",
    } <= set(SUPPORTED_PROJECT_TYPES)


def test_create_project_scaffold_creates_repo_and_expected_files(
    builder: GitHubAgentBuilder,
) -> None:
    result = builder.create_project_scaffold(
        "demo-web",
        "Web Builder demo",
        "web_builder",
    )

    assert result.startswith("Repozytorium wdrożone pomyślnie.")
    repo = builder.gh.get_user().repos[0]
    paths = [item[0] for item in repo.files]

    assert paths == ["README.md", "index.html"]
    assert all(item[3] == "main" for item in repo.files)
    assert "Scaffold Modules" in repo.files[0][2]


def test_create_project_scaffold_rejects_unknown_project_type(
    builder: GitHubAgentBuilder,
) -> None:
    with pytest.raises(ValueError, match="Nieobsługiwany typ projektu"):
        builder.create_project_scaffold("demo", "Demo", "unknown")


def test_pull_request_and_issue_are_created_on_remote_repo(
    builder: GitHubAgentBuilder,
) -> None:
    builder.create_project_scaffold("demo", "Demo", "app_builder")

    pr_result = builder.automate_pull_request(
        "demo",
        "Add feature",
        "Generated by Agent Devel.",
        "agent/feature",
        "main",
    )
    issue_result = builder.report_retrospective_issue(
        "demo",
        "Build failure",
        "CI failed.",
    )

    repo = builder.gh.get_user().repos[0]
    assert "pull/1" in pr_result
    assert "issues/1" in issue_result
    assert repo.pull_requests[0]["head"] == "agent/feature"
    assert repo.pull_requests[0]["base"] == "main"
    assert repo.issues[0]["title"] == "Build failure"


def test_token_is_required() -> None:
    with pytest.raises(ValueError, match="token"):
        GitHubAgentBuilder("")


def test_scaffold_does_not_define_runtime_execution_hooks(
    builder: GitHubAgentBuilder,
) -> None:
    builder.create_project_scaffold("demo", "Demo", "game_builder")
    repo = builder.gh.get_user().repos[0]
    combined = "\n".join(item[2] for item in repo.files)

    assert "subprocess" not in combined
    assert "os.system" not in combined
