package com.mobilefork.hermesagent.ui.chat

import com.mobilefork.hermesagent.R

data class SignalIntelligenceQuickAction(
    val id: String,
    val label: String,
    val diagnosticAction: String,
    val prompt: String,
    val iconRes: Int,
)

val SIGNAL_INTELLIGENCE_QUICK_ACTIONS = listOf(
    SignalIntelligenceQuickAction(
        id = "signal_overview",
        label = "Signal Overview",
        diagnosticAction = "signal_awareness_report",
        prompt = "Run android_device_diagnostics_tool action=signal_awareness_report",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "signal_briefing",
        label = "Signal Briefing",
        diagnosticAction = "agent_signal_briefing_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_briefing_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "signal_session_snapshot",
        label = "Session Snapshot",
        diagnosticAction = "agent_signal_session_snapshot_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_session_snapshot_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "signal_proof_audit",
        label = "Proof Audit",
        diagnosticAction = "agent_signal_proof_audit_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_proof_audit_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "signal_replay_export",
        label = "Replay Export",
        diagnosticAction = "agent_signal_replay_export_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_replay_export_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "signal_replay_freshness",
        label = "Replay Freshness",
        diagnosticAction = "agent_signal_replay_freshness_audit_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_replay_freshness_audit_report",
        iconRes = R.drawable.ic_action_refresh,
    ),
    SignalIntelligenceQuickAction(
        id = "signal_observation_packet",
        label = "Sight Packet",
        diagnosticAction = "agent_signal_observation_packet_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_observation_packet_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "signal_card_deck",
        label = "Card Deck",
        diagnosticAction = "agent_signal_card_deck_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_card_deck_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "card_refresh_plan",
        label = "Refresh Plan",
        diagnosticAction = "agent_signal_card_refresh_plan_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_card_refresh_plan_report",
        iconRes = R.drawable.ic_action_refresh,
    ),
    SignalIntelligenceQuickAction(
        id = "card_refresh_status",
        label = "Refresh Status",
        diagnosticAction = "agent_signal_card_refresh_status_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_card_refresh_status_report",
        iconRes = R.drawable.ic_action_refresh,
    ),
    SignalIntelligenceQuickAction(
        id = "signal_timeline",
        label = "Signal Timeline",
        diagnosticAction = "agent_signal_timeline_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_timeline_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "signal_evidence",
        label = "Evidence Bundle",
        diagnosticAction = "agent_signal_evidence_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_evidence_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "workflow_handoff",
        label = "Workflow Handoff",
        diagnosticAction = "agent_signal_workflow_handoff_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_workflow_handoff_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "permission_runbook",
        label = "Permission Runbook",
        diagnosticAction = "agent_signal_permission_runbook_report",
        prompt = "Run android_device_diagnostics_tool action=agent_signal_permission_runbook_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "rf_coexistence",
        label = "RF Coexistence",
        diagnosticAction = "rf_coexistence_report",
        prompt = "Run android_device_diagnostics_tool action=rf_coexistence_report refresh=false",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "agent_environment",
        label = "Agent Environment",
        diagnosticAction = "agent_environment_report",
        prompt = "Run android_device_diagnostics_tool action=agent_environment_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "agent_self_check",
        label = "Self-Check",
        diagnosticAction = "agent_self_check_report",
        prompt = "Run android_device_diagnostics_tool action=agent_self_check_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "agent_observation",
        label = "Agent Observation",
        diagnosticAction = "agent_observation_report",
        prompt = "Run android_device_diagnostics_tool action=agent_observation_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "card_manifest",
        label = "Card Manifest",
        diagnosticAction = "agent_card_manifest_report",
        prompt = "Run android_device_diagnostics_tool action=agent_card_manifest_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "top_cards",
        label = "Top Cards",
        diagnosticAction = "agent_card_priority_report",
        prompt = "Run android_device_diagnostics_tool action=agent_card_priority_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "mcp_registry",
        label = "MCP Registry",
        diagnosticAction = "mcp_tool_server_registry_report",
        prompt = "Run android_device_diagnostics_tool action=mcp_tool_server_registry_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "upgrade_audit",
        label = "Upgrade Audit",
        diagnosticAction = "agent_capability_upgrade_report",
        prompt = "Run android_device_diagnostics_tool action=agent_capability_upgrade_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "objective_coverage",
        label = "Objective Coverage",
        diagnosticAction = "agent_objective_coverage_report",
        prompt = "Run android_device_diagnostics_tool action=agent_objective_coverage_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "release_validation",
        label = "Release Validation",
        diagnosticAction = "agent_release_validation_report",
        prompt = "Run android_device_diagnostics_tool action=agent_release_validation_report",
        iconRes = R.drawable.ic_nav_hermes,
    ),
    SignalIntelligenceQuickAction(
        id = "soc_compatibility",
        label = "SOC Compatibility",
        diagnosticAction = "soc_compatibility_report",
        prompt = "Run android_device_diagnostics_tool action=soc_compatibility_report",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "mediatek_readiness",
        label = "MediaTek Readiness",
        diagnosticAction = "mediatek_readiness_report",
        prompt = "Run android_device_diagnostics_tool action=mediatek_readiness_report",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "mediatek_signal_stack",
        label = "MTK Signals",
        diagnosticAction = "mediatek_signal_stack_report",
        prompt = "Run android_device_diagnostics_tool action=mediatek_signal_stack_report",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "mediatek_device_validation",
        label = "Device Proof",
        diagnosticAction = "mediatek_device_validation_report",
        prompt = "Run android_device_diagnostics_tool action=mediatek_device_validation_report",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "device_evidence_export",
        label = "Proof Export",
        diagnosticAction = "device_validation_evidence_export_report",
        prompt = "Run android_device_diagnostics_tool action=device_validation_evidence_export_report",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "accelerator_preflight",
        label = "Accel Preflight",
        diagnosticAction = "accelerator_preflight_report",
        prompt = "Run android_device_diagnostics_tool action=accelerator_preflight_report",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "non_adreno_backend_advisor",
        label = "Backend Advisor",
        diagnosticAction = "non_adreno_backend_advisor_report",
        prompt = "Run android_device_diagnostics_tool action=non_adreno_backend_advisor_report",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "mediatek_launch_checklist",
        label = "MTK Launch",
        diagnosticAction = "mediatek_backend_launch_checklist_report",
        prompt = "Run android_device_diagnostics_tool action=mediatek_backend_launch_checklist_report",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "backend_risk",
        label = "Backend Risk",
        diagnosticAction = "gpu_backend_risk_report",
        prompt = "Run android_device_diagnostics_tool action=gpu_backend_risk_report",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "inference_compatibility",
        label = "Inference Fit",
        diagnosticAction = "local_inference_compatibility_report",
        prompt = "Run android_device_diagnostics_tool action=local_inference_compatibility_report",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "runtime_backend",
        label = "Runtime Backend",
        diagnosticAction = "local_backend_runtime_report",
        prompt = "Run android_device_diagnostics_tool action=local_backend_runtime_report",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "runtime_stability",
        label = "Runtime Stability",
        diagnosticAction = "device_performance_report",
        prompt = "Run android_device_diagnostics_tool action=device_performance_report",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "wifi_analyzer",
        label = "Wi-Fi Analyzer",
        diagnosticAction = "wifi_analyzer_report",
        prompt = "Run android_device_diagnostics_tool action=wifi_analyzer_report refresh=false",
        iconRes = R.drawable.ic_action_refresh,
    ),
    SignalIntelligenceQuickAction(
        id = "wifi_advisor",
        label = "Wi-Fi Advisor",
        diagnosticAction = "wifi_signal_advisor_report",
        prompt = "Run android_device_diagnostics_tool action=wifi_signal_advisor_report refresh=false",
        iconRes = R.drawable.ic_action_refresh,
    ),
    SignalIntelligenceQuickAction(
        id = "wifi_channel_decision",
        label = "Wi-Fi Decision",
        diagnosticAction = "wifi_channel_decision_packet_report",
        prompt = "Run android_device_diagnostics_tool action=wifi_channel_decision_packet_report refresh=false",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "wifi_link",
        label = "Wi-Fi Link",
        diagnosticAction = "wifi_connection_link",
        prompt = "Run android_device_diagnostics_tool action=wifi_connection_link",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "wifi_nearby",
        label = "Nearby Wi-Fi",
        diagnosticAction = "wifi_scan",
        prompt = "Run android_device_diagnostics_tool action=wifi_scan refresh=false",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "wifi_occupancy",
        label = "Wi-Fi Occupancy",
        diagnosticAction = "wifi_channel_utilization",
        prompt = "Run android_device_diagnostics_tool action=wifi_channel_utilization refresh=false",
        iconRes = R.drawable.ic_action_refresh,
    ),
    SignalIntelligenceQuickAction(
        id = "bluetooth_analyzer",
        label = "Bluetooth Analyzer",
        diagnosticAction = "bluetooth_analyzer_report",
        prompt = "Run android_device_diagnostics_tool action=bluetooth_analyzer_report refresh=false",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "bluetooth_advisor",
        label = "Bluetooth Advisor",
        diagnosticAction = "bluetooth_signal_advisor_report",
        prompt = "Run android_device_diagnostics_tool action=bluetooth_signal_advisor_report refresh=false",
        iconRes = R.drawable.ic_action_refresh,
    ),
    SignalIntelligenceQuickAction(
        id = "bluetooth_decision",
        label = "BT Decision",
        diagnosticAction = "bluetooth_nearby_decision_packet_report",
        prompt = "Run android_device_diagnostics_tool action=bluetooth_nearby_decision_packet_report refresh=false",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "bluetooth_history",
        label = "Bluetooth Trends",
        diagnosticAction = "bluetooth_signal_history",
        prompt = "Run android_device_diagnostics_tool action=bluetooth_signal_history refresh=false",
        iconRes = R.drawable.ic_action_refresh,
    ),
    SignalIntelligenceQuickAction(
        id = "bluetooth_details",
        label = "Bluetooth Details",
        diagnosticAction = "bluetooth_device_details",
        prompt = "Run android_device_diagnostics_tool action=bluetooth_device_details refresh=false",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "sensor_analyzer",
        label = "Sensor Analyzer",
        diagnosticAction = "sensor_analyzer_report",
        prompt = "Run android_device_diagnostics_tool action=sensor_analyzer_report include_snapshot=false",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "sensor_advisor",
        label = "Sensor Advisor",
        diagnosticAction = "sensor_workflow_advisor_report",
        prompt = "Run android_device_diagnostics_tool action=sensor_workflow_advisor_report include_snapshot=false",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "motion_decision",
        label = "Motion Decision",
        diagnosticAction = "motion_sensor_decision_packet_report",
        prompt = "Run android_device_diagnostics_tool action=motion_sensor_decision_packet_report include_snapshot=false",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "motion_history",
        label = "Motion Trends",
        diagnosticAction = "motion_sensor_history",
        prompt = "Run android_device_diagnostics_tool action=motion_sensor_history sample=true sensor_types=accelerometer,gyroscope,linear_acceleration,rotation_vector",
        iconRes = R.drawable.ic_action_refresh,
    ),
    SignalIntelligenceQuickAction(
        id = "motion_quality",
        label = "Motion Quality",
        diagnosticAction = "motion_sensor_quality",
        prompt = "Run android_device_diagnostics_tool action=motion_sensor_quality include_snapshot=false",
        iconRes = R.drawable.ic_nav_device,
    ),
    SignalIntelligenceQuickAction(
        id = "radio_limits",
        label = "Radio Signals",
        diagnosticAction = "radio_signal_graph",
        prompt = "Run android_device_diagnostics_tool action=radio_signal_graph",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "radio_advisor",
        label = "Radio Advisor",
        diagnosticAction = "radio_signal_advisor_report",
        prompt = "Run android_device_diagnostics_tool action=radio_signal_advisor_report",
        iconRes = R.drawable.ic_action_cog,
    ),
    SignalIntelligenceQuickAction(
        id = "radio_decision",
        label = "Radio Decision",
        diagnosticAction = "radio_signal_decision_packet_report",
        prompt = "Run android_device_diagnostics_tool action=radio_signal_decision_packet_report",
        iconRes = R.drawable.ic_nav_device,
    ),
)
